baseURL = "https://shirazlug.ir/"
languageCode = "fa-IR"
title = "شیرازلاگ"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "شیرازلاگ"
    description = "به شیرازلاگ خوش آمدید :) لاگ به معنی گروه کاربران گنو/لینوکس است و از افراد مختلف که به منظور تبادل اطلاعات در حوزه‌ی نرم‌افزارهای آزاد و متن‌باز دور هم جمع می‌شوند، تشکیل شده است. اگر تمایل دارید دانش خود را با دیگران به اشتراک بگذارید یا کنجکاوید تا از تکنولوژی‌های آزاد جدید اطلاعاتی کسب کنید و یا از بودن در کنار چند دوست فعال در این زمینه لذت می‌برید، با ما همراه شوید. در ضمن، شرکت در جلسات برای عموم آزاد و رایگان است."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Vazir"#"Raleway" #vazir  # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "c++", "c", "python", "ruby"]
    address = "آدرس: خ همت جنوبی، کوچه ۱۰/۲، سالن همایش امام رضا (ع)"
    # address = "آدرس: بولوار مدرس، روبروی فضل آباد، دانشگاه صنعتی شیراز"
[[menu.main]]
    url = "/"
    name = "خانه"
    weight = 6

[[menu.main]]
    url = "/session/"
    name = "جلسه‌های لاگ"
    weight = 5

[[menu.main]]
    url = "/post/"
    name = "پست های آزاد"
    weight = 4

[[menu.main]]
    url = "/new/"
    name = "اخبار"
    weight = 3

[[menu.main]]
    url = "/event/"
    name = "رویداد ها"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "درباره ما"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://osm.org/go/zGYksxTI0-?layers=N"
    name = "map-marker"
    weight = 7

[[menu.icon]]
    url = "mailto:contact@shirazlug.ir"
    name = "envelope-o"
    weight = 6

[[menu.icon]]
    url = "https://telegram.me/joinchat/AYtPuT58Mz94GAd_-NxodQ"
    name = "telegram"
    weight = 5

[[menu.icon]]
    url = "https://github.com/shirazlug/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.instagram.com/ShirazLUG.ir/"
    name = "instagram"
    weight = 4


[[menu.icon]]
    url = "https://twitter.com/ShirazLUG_ir"
    name = "twitter"
    weight = 3


[[menu.icon]]
    url = "https://www.linkedin.com/groups/8644227"
    name = "linkedin"
    weight = 8

[[menu.icon]]
    url = "https://www.facebook.com/ShirazLUG.ir/"
    name = "facebook"
    weight = 9

[[menu.icon]]
    url = "https://gitlab.com/shirazlug"
    name = "gitlab"
    weight = 1
